### PR TITLE
Add query generator

### PR DESCRIPTION
**Pull request by yamalight**
Adds query generator for #4

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks! Let me go through the commits, consolidate them, add a README, and I'll merge.

**Comment by RubenVerborgh** [comment]
BTW By what name may I credit you in the README? :wink:

**Comment by yamalight** [comment]
@RubenVerborgh Ah, totally forgot about that part :smile: 
`Tim Ermilov <yamalight@gmail.com>`

**Comment by RubenVerborgh** [comment]
Could you please fix these issues?
- Looks like there's a bad merge: all commits appear twice. I'd suggest rebasing on the current master branch, ensuring that all commits appear once
- Running `npm test` only runs the generator tests, not the parser tests (for some reason I can't immediately figure out).

I'll then make some further edits before merging.

**Comment by yamalight** [comment]
Okay, will rebase to make it look nice.
And yes, will fix the test, forgot to remove .only() part, being silly >_>

**Comment by yamalight** [comment]
okay, all fixed, rebased and pushed.

**Comment by RubenVerborgh** [comment]
Thanks, will review in-depth and then merge. Excellent work!

**Comment by yamalight** [comment]
@RubenVerborgh any updates? :smile:

**Comment by RubenVerborgh** [comment]
Still traveling; on to-do list.

**Comment by yamalight** [comment]
okay, cool. please, ping me once it's merged :)

**Comment by RubenVerborgh** [comment]
FYI I'm still working on this, but some things are taking a bit more time than expected. Some things, while working as intended, do not accurately reflect functionality. For instance:
```
var varSymbols = ['?', '_:', '"', '*']; // symbols presence of which means that string is SPARQL variable
```

So sorry for the delay, but I'm taking quality control very seriously :wink:

**Comment by yamalight** [comment]
sounds good! :+1:

**Comment by RubenVerborgh** [comment]
Thanks for implementing this. Merged in master!
Please let me know if everything looks alright to you; if so, I'll do a new release.

**Comment by yamalight** [comment]
had a quick look - seems to be good. 
that's some nice work on improvements! :)

**Comment by RubenVerborgh** [comment]
Thx! Will document interface and release a version one of these days.

**Comment by yamalight** [comment]
cool! :smile_cat:

**Comment by RubenVerborgh** [comment]
Released as v1.1.0.

**Comment by yamalight** [comment]
awesome! now to update the deps.. :D

**Pull request closed without merging**
