### PR TITLE
Run SPARQL test suite on Travis builds

### PR DESCRIPTION
**Pull request by rubensworks**
This adds [rdf-test-suite](https://github.com/rubensworks/rdf-test-suite.js) as a dev dependency to run the SPARQL query and update test suite.
It skips all tests that execute queries, and only runs the syntax tests.

At the moment, a few query tests fail (those reported in https://github.com/comunica/comunica/issues/287), but also a few update queries fail that have not been reported before.

For the moment, I've added the `-e` flag to disable Travis build failures on test failures. Once spec compliance is restored, this flag should be removed to detect future regressions.

### CODE REVIEW

**Comment by rubensworks** [comment]
Oops, indentation issue in yaml, fixed now.

**Comment by RubenVerborgh** [comment]
Node 6 fail, but okay with dropping support.

**Comment by rubensworks** [comment]
Ok, shall I also update minimum support in package.json engines, or leave as-is?

**Comment by RubenVerborgh** [comment]
If you want, yes.

**Comment by rubensworks** [comment]
Oh, it's already set to Node 8 there, nvm.

**Comment by rubensworks** [comment]
I assume this can be merged?

**Comment by RubenVerborgh** [comment]
Yes, thanks!

**Pull request merged**
