### PR TITLE
correctly handle the full URIs of the literal datatypes

### PR DESCRIPTION
**Pull request by joachimvh**
I admit, I did this instead of a mail just to look cool.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
I prefer pull requests over mails 😄 

However, the [N3.js representation](https://github.com/RubenVerborgh/N3.js#utility) does not use angular brackets for IRIs, also not for datatypes. So SPARQL.js is consistent with that.

**Comment by joachimvh** [comment]
You know, I vaguely seem to recall having this exact same discussion a year ago about the fact that this is wrong in my opinion. :D

**Comment by RubenVerborgh** [comment]
It's not really a matter of right or wrong, it's just a design decision 😄 

I just chose to represent IRIs without angular brackets for simplicity, and to be independent of a particular syntax.

**Comment by joachimvh** [comment]
True, 'wrong' wasn't the correct word to use here. You could even say it was the wrong word! (Sorry :stuck_out_tongue_closed_eyes: ).
Reason for asking btw is because I'm looking at my SPARQL algebra generator again and this caused it to contain invalid URIs. So best solution is to use some form of regex to handle this?

**Comment by RubenVerborgh** [comment]
It depends—what syntax does your SPARQL algebra generator use? If it is Turtle, you should use a Turtle serializer (the one in N3.js would do great).

If it is something else, but uses Turtle-style literals, you will need to do more than just adding `<>`, since some characters will need to be escaped. [See this example.](https://github.com/RubenVerborgh/SPARQL.js/blob/v1.1.4/lib/SparqlGenerator.js#L188-L194)

**Pull request closed without merging**
