### PR TITLE
Fix generation of queries with multiline literals

### PR DESCRIPTION
**Pull request by yamalight**

### CODE REVIEW

**Comment by yamalight** [comment]
@RubenVerborgh would appreciate if you can merge this quickly :)

**Comment by yamalight** [comment]
@RubenVerborgh updated!

**Comment by RubenVerborgh** [comment]
Thanks for this! Released as v1.1.3.

**Comment by yamalight** [comment]
@RubenVerborgh awesome, thanks! :+1:

**Comment by seebi** [comment]
:+1:  for the quick merge :-)

**Pull request merged**
