### PR TITLE
Disable explicit group pattern collapse

### LINKED ISSUE #35: Disable (minor) query rewrites by default
Let's say we have a simple query like:

```sparql
SELECT * WHERE {
  { ?s ?p ?o. }
  ?a ?b ?c .
}
```
With the last SPARQL.js it is parsed to: 

```json
{
  "queryType": "SELECT",
  "variables": [
    "*"
  ],
  "where": [
    {
      "type": "bgp",
      "triples": [
        {
          "subject": "?s",
          "predicate": "?p",
          "object": "?o"
        },
        {
          "subject": "?a",
          "predicate": "?b",
          "object": "?c"
        }
      ]
    }
  ],
  "type": "query",
  "prefixes": {}
}
```

Which doesn't correspond to the original query, if I serialize it, the result will be: 

```sparql
SELECT * WHERE {
  ?s ?p ?o.
  ?a ?b ?c .
}
```

This missing group sometimes can be significant, e.g. in my use-case I'm trying to apply blazegraph(https://wiki.blazegraph.com/wiki/index.php/QueryHints) query hint to the subgroup.

### PR DESCRIPTION
**Pull request by AlexeyMz**
Closes #35.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Makes sense, thanks. Let me think about this for a bit, and I'll merge.

**Comment by RubenVerborgh** [comment]
The problem is basically that this would break backward compatibility, so we'd need a new major version. So I'm considering whether this is the way to go, or whether this should be behind a flag until the next major version. It might still be useful to place the algorithm somewhere.

**Comment by AlexeyMz** [comment]
I think it would be fine to keep the changes under a flag to preserve compatibility for now.

**Comment by RubenVerborgh** [comment]
Alright, would you mind adding that?

**Comment by AlexeyMz** [comment]
I added `collapseGroups` flag (enabled by default).

**Comment by RubenVerborgh** [comment]
Thanks, will take this up ASAP!

**Comment by RubenVerborgh** [comment]
Merged as b259983b1d91461cfb91af55750606a7100f8e15.

**Pull request closed without merging**
